<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    /**
     * Save
     *
     * @param \AppBundle\Entity\User $entity
     * @return bool
     */
    public function save(User $entity)
    {
        try {
            $this->getEntityManager()->persist($entity);
            $this->getEntityManager()->flush();
        } catch (\PDOException $e) {
            return false;
        }

        return true;
    }

    /**
     * Delete
     *
     * @param \AppBundle\Entity\User $entity
     * @return bool
     */
    public function delete(User $entity)
    {
        try {
            $this->getEntityManager()->remove($entity);
            $this->getEntityManager()->flush();
        } catch (\PDOException $e) {
            return false;
        }

        return true;
    }
    /**
     * Pagination qb
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getPaginationQB()
    {
        return $this->createQueryBuilder('u')->orderBy('u.id');
    }
}
